# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sasha/Code/infinite/source

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sasha/Code/infinite/source

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sasha/Code/infinite/source/CMakeFiles /home/sasha/Code/infinite/source//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sasha/Code/infinite/source/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

camera.o: camera.cpp.o
.PHONY : camera.o

# target to build an object file
camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/camera.cpp.o
.PHONY : camera.cpp.o

camera.i: camera.cpp.i
.PHONY : camera.i

# target to preprocess a source file
camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/camera.cpp.i
.PHONY : camera.cpp.i

camera.s: camera.cpp.s
.PHONY : camera.s

# target to generate assembly for a file
camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/camera.cpp.s
.PHONY : camera.cpp.s

chunk.o: chunk.cpp.o
.PHONY : chunk.o

# target to build an object file
chunk.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/chunk.cpp.o
.PHONY : chunk.cpp.o

chunk.i: chunk.cpp.i
.PHONY : chunk.i

# target to preprocess a source file
chunk.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/chunk.cpp.i
.PHONY : chunk.cpp.i

chunk.s: chunk.cpp.s
.PHONY : chunk.s

# target to generate assembly for a file
chunk.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/chunk.cpp.s
.PHONY : chunk.cpp.s

dynamic_indices.o: dynamic_indices.cpp.o
.PHONY : dynamic_indices.o

# target to build an object file
dynamic_indices.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/dynamic_indices.cpp.o
.PHONY : dynamic_indices.cpp.o

dynamic_indices.i: dynamic_indices.cpp.i
.PHONY : dynamic_indices.i

# target to preprocess a source file
dynamic_indices.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/dynamic_indices.cpp.i
.PHONY : dynamic_indices.cpp.i

dynamic_indices.s: dynamic_indices.cpp.s
.PHONY : dynamic_indices.s

# target to generate assembly for a file
dynamic_indices.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/dynamic_indices.cpp.s
.PHONY : dynamic_indices.cpp.s

glad.o: glad.c.o
.PHONY : glad.o

# target to build an object file
glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/glad.c.o
.PHONY : glad.c.o

glad.i: glad.c.i
.PHONY : glad.i

# target to preprocess a source file
glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/glad.c.i
.PHONY : glad.c.i

glad.s: glad.c.s
.PHONY : glad.s

# target to generate assembly for a file
glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/glad.c.s
.PHONY : glad.c.s

gradient.o: gradient.cpp.o
.PHONY : gradient.o

# target to build an object file
gradient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/gradient.cpp.o
.PHONY : gradient.cpp.o

gradient.i: gradient.cpp.i
.PHONY : gradient.i

# target to preprocess a source file
gradient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/gradient.cpp.i
.PHONY : gradient.cpp.i

gradient.s: gradient.cpp.s
.PHONY : gradient.s

# target to generate assembly for a file
gradient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/gradient.cpp.s
.PHONY : gradient.cpp.s

gradient_field.o: gradient_field.cpp.o
.PHONY : gradient_field.o

# target to build an object file
gradient_field.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/gradient_field.cpp.o
.PHONY : gradient_field.cpp.o

gradient_field.i: gradient_field.cpp.i
.PHONY : gradient_field.i

# target to preprocess a source file
gradient_field.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/gradient_field.cpp.i
.PHONY : gradient_field.cpp.i

gradient_field.s: gradient_field.cpp.s
.PHONY : gradient_field.s

# target to generate assembly for a file
gradient_field.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/gradient_field.cpp.s
.PHONY : gradient_field.cpp.s

light.o: light.cpp.o
.PHONY : light.o

# target to build an object file
light.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/light.cpp.o
.PHONY : light.cpp.o

light.i: light.cpp.i
.PHONY : light.i

# target to preprocess a source file
light.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/light.cpp.i
.PHONY : light.cpp.i

light.s: light.cpp.s
.PHONY : light.s

# target to generate assembly for a file
light.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/light.cpp.s
.PHONY : light.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

renderer.o: renderer.cpp.o
.PHONY : renderer.o

# target to build an object file
renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/renderer.cpp.o
.PHONY : renderer.cpp.o

renderer.i: renderer.cpp.i
.PHONY : renderer.i

# target to preprocess a source file
renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/renderer.cpp.i
.PHONY : renderer.cpp.i

renderer.s: renderer.cpp.s
.PHONY : renderer.s

# target to generate assembly for a file
renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/renderer.cpp.s
.PHONY : renderer.cpp.s

shader.o: shader.cpp.o
.PHONY : shader.o

# target to build an object file
shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/shader.cpp.o
.PHONY : shader.cpp.o

shader.i: shader.cpp.i
.PHONY : shader.i

# target to preprocess a source file
shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/shader.cpp.i
.PHONY : shader.cpp.i

shader.s: shader.cpp.s
.PHONY : shader.s

# target to generate assembly for a file
shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/shader.cpp.s
.PHONY : shader.cpp.s

sun.o: sun.cpp.o
.PHONY : sun.o

# target to build an object file
sun.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/sun.cpp.o
.PHONY : sun.cpp.o

sun.i: sun.cpp.i
.PHONY : sun.i

# target to preprocess a source file
sun.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/sun.cpp.i
.PHONY : sun.cpp.i

sun.s: sun.cpp.s
.PHONY : sun.s

# target to generate assembly for a file
sun.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/sun.cpp.s
.PHONY : sun.cpp.s

terrain.o: terrain.cpp.o
.PHONY : terrain.o

# target to build an object file
terrain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/terrain.cpp.o
.PHONY : terrain.cpp.o

terrain.i: terrain.cpp.i
.PHONY : terrain.i

# target to preprocess a source file
terrain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/terrain.cpp.i
.PHONY : terrain.cpp.i

terrain.s: terrain.cpp.s
.PHONY : terrain.s

# target to generate assembly for a file
terrain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/terrain.cpp.s
.PHONY : terrain.cpp.s

texture.o: texture.cpp.o
.PHONY : texture.o

# target to build an object file
texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/texture.cpp.o
.PHONY : texture.cpp.o

texture.i: texture.cpp.i
.PHONY : texture.i

# target to preprocess a source file
texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/texture.cpp.i
.PHONY : texture.cpp.i

texture.s: texture.cpp.s
.PHONY : texture.s

# target to generate assembly for a file
texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/texture.cpp.s
.PHONY : texture.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... camera.o"
	@echo "... camera.i"
	@echo "... camera.s"
	@echo "... chunk.o"
	@echo "... chunk.i"
	@echo "... chunk.s"
	@echo "... dynamic_indices.o"
	@echo "... dynamic_indices.i"
	@echo "... dynamic_indices.s"
	@echo "... glad.o"
	@echo "... glad.i"
	@echo "... glad.s"
	@echo "... gradient.o"
	@echo "... gradient.i"
	@echo "... gradient.s"
	@echo "... gradient_field.o"
	@echo "... gradient_field.i"
	@echo "... gradient_field.s"
	@echo "... light.o"
	@echo "... light.i"
	@echo "... light.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... renderer.o"
	@echo "... renderer.i"
	@echo "... renderer.s"
	@echo "... shader.o"
	@echo "... shader.i"
	@echo "... shader.s"
	@echo "... sun.o"
	@echo "... sun.i"
	@echo "... sun.s"
	@echo "... terrain.o"
	@echo "... terrain.i"
	@echo "... terrain.s"
	@echo "... texture.o"
	@echo "... texture.i"
	@echo "... texture.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

